### ISSUE TITLE
Feedback #7: Layout restructure on the Geography Page

### ISSUE THREAD

**Issue by kipiiler** [kipiiler/CBR-fishModel#1]
# Description
Change the layout of the geography page to match with the following image:

![image](https://user-images.githubusercontent.com/56223669/222004419-3e88a49a-f756-4808-b606-9d733e2ba732.png)

# Tasks
- [x] Update layout & styling
- [x] Zoom out on the map component to include all points & the San Frisco city's dot.
- [ ] Using the ImageDisplayer component for all the images.  `src\components\Utils\ImageDisplayer.jsx`
- [ ] Add a new image on the corner right
